# Generated by Django 3.2 on 2021-06-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
