# Generated by Django 3.2 on 2021-06-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_employeemodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='profile_pic',
        ),
    ]
