# Generated by Django 3.2 on 2021-06-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razor',
            name='orders',
        ),
    ]
